### ISSUE TITLE
status of this project ?

### ISSUE THREAD

**Issue by noelzubin** [ssosik/xapian-query-cli#11]
Hi @ssosik . I was foraging the web for personal notes indexer. I was about to write one myself with tantivy and tui-rs when i stumbled upon your project. Since its been a while I was wondering if you use this app or any other notes search tools now. I would also like to contribute to this project if you think that you find this app useful. 😛

**Comment by ssosik** [comment]
Hi @noelzubin!

I haven't had time to keep this going. I've switched to using Notion. Feel free to fork and poke at this, it worked alright. I had previously used Xapian for document indexing and querying, and I found that I didn't like Tantivy as much. But building against Xapian in a mutliplatform way was too finicky for me.

**Comment by noelzubin** [comment]
Interesting! How has your experience been with Notion so far? Personally, I'm a bit hesitant to transition from markdown files and the terminal. By the way, Xapian seems promising. Thank you for sharing!". I will take a poke at this.
